import { persona } from "../persona.config";

const n = persona.name;

export const STR = {
  gameTitle: `${n.toUpperCase()}'S WORLDS`,
  tapToStart: "Tap to begin",
  welcomeBack: `Welcome back, ${persona.title} ${n}!`,
  newAdventure: `A whole universe is waiting, ${n}.`,
  continueBtn: "Continue",
  startBtn: "Blast Off!",
  baseTitle: `${n.toUpperCase()}'S BASE`,
  missionBoard: "Mission Board",
  goBtn: "Go!",
  workshop: "Workshop",
  trophyShelf: "Trophy Shelf",
  trophyEmpty: "Your first trophy is waiting…",
  comingSoon: "Soon",
  almostLook: "Almost — look at this.",
  lookExample: "Look:",
  greatJob: ["Great!", "Yes!", "Nice one!", "You got it!", "Brilliant!"],
  perfectRun: "Perfect Run!",
  proveAgain: "Yes! One more to prove it…",
  thinkFirst: "🤔 Think about it first…",
  howToPlay: "How to play",
  companionSlow: `Take your time, ${persona.title} ${n} — the Forge isn't going anywhere.`,
  stageComplete: "Gate cleared!",
  replayNote: "Replay reward",
  backToMap: "Back to Map",
  nextStage: "Next Stage",
  playAgain: "Play Again",
  notEnough: "Not enough Star Dust yet!",
  owned: "In your base",
  buy: "Buy",
  continueBar: "Continue",
  daddyRewards: "Daddy Rewards",
  tellDaddy: (reward: string) => `Tell Daddy: I earned ${reward}!`,
  daddyOk: "Daddy said yes! ✓",
  later: "Later",
  decorations: "Decorations",
  couponSection: "Daddy Rewards — buy, then show Daddy!",
  question: (i: number, total: number) => `${i} of ${total}`,
  badgeEarned: "New Trophy!",
  // Cosmo — the companion
  petEggTitle: `A mystery egg appeared, ${n}!`,
  petEggSub: "Give it a name to hatch it 🥚",
  petNamePlaceholder: "Name your buddy…",
  petHatchBtn: "Hatch! ✨",
  petHappy: (name: string) => `${name} is happy and full ✨`,
  petPeckish: (name: string) => `${name} is getting peckish 🍃`,
  petHungry: (name: string) => `${name} is hungry — answer questions to feed it! 🍙`,
  petMaxed: (name: string) => `${name} is fully grown — a legend! 🌟`,
  petToNext: (meals: number, label: string) =>
    `${meals} more ${meals === 1 ? "meal" : "meals"} → ${label}!`,
  petEvolved: (name: string, label: string) => `${name} grew into a ${label}! 🎉`,
  petTapLine: (name: string) => `${name} loves you, ${n}! 💖`,
} as const;
