import { persona } from "../persona.config";

const n = persona.name;

export const STR = {
  gameTitle: `${n.toUpperCase()}'S WORLDS`,
  tapToStart: "Tap to begin",
  welcomeBack: `Welcome back, ${persona.title} ${n}!`,
  newAdventure: `A whole universe is waiting, ${n}.`,
  continueBtn: "Continue",
  startBtn: "Blast Off!",
  baseTitle: `${n.toUpperCase()}'S BASE`,
  missionBoard: "Mission Board",
  goBtn: "Go!",
  workshop: "Workshop",
  trophyShelf: "Trophy Shelf",
  trophyEmpty: "Your first trophy is waiting…",
  comingSoon: "Soon",
  almostLook: "Almost — look at this.",
  lookExample: "Look:",
  greatJob: ["Great!", "Yes!", "Nice one!", "You got it!", "Brilliant!"],
  perfectRun: "Perfect Run!",
  proveAgain: "Yes! One more to prove it…",
  thinkFirst: "🤔 Think about it first…",
  howToPlay: "How to play",
  companionSlow: `Take your time, ${persona.title} ${n} — the Forge isn't going anywhere.`,
  stageComplete: "Gate cleared!",
  replayNote: "Replay reward",
  backToMap: "Back to Map",
  nextStage: "Next Stage",
  playAgain: "Play Again",
  notEnough: "Not enough Star Dust yet!",
  owned: "In your base",
  buy: "Buy",
  continueBar: "Continue",
  daddyRewards: "Daddy Rewards",
  tellDaddy: (reward: string) => `Tell Daddy: I earned ${reward}!`,
  daddyOk: "Daddy said yes! ✓",
  later: "Later",
  decorations: "Decorations",
  couponSection: "Daddy Rewards — buy, then show Daddy!",
  question: (i: number, total: number) => `${i} of ${total}`,
  badgeEarned: "New Trophy!",
} as const;
